version: "3.7"
services:
  web-server:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    volumes:
      - "./html/:/var/www/html/"
    command: >
      sh -c "
      mkdir -p /var/www/html/admin/temp_word && 
      chown -R www-data:www-data /var/www/html/admin/temp_word && 
      chmod -R 777 /var/www/html/admin/temp_word && 
      apache2-foreground"
    ports:
      - "8080:80"
  mysql-server:
    image: mysql:8.0.44
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.3
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "8081:80"
volumes:
  mysql-data:
